"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from config.env_parser import get_env_time_interval, get_env_int

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is now inside backend/. So backend/ = BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from ../infra/.env
load_dotenv(BASE_DIR.parent / 'infra' / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = bool(int(os.environ.get('DJANGO_DEBUG', '0')))

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me')
# В проде дефолтный ключ недопустим: SECRET_KEY здесь же подписывает JWT
# (SIMPLE_JWT без отдельного SIGNING_KEY), поэтому предсказуемый ключ = подделка
# токенов на любого пользователя. Падаем сразу, а не втихую поднимаемся с ним.
if not DEBUG and SECRET_KEY == 'change-me':
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY не задан в проде (DJANGO_DEBUG=0). '
        'Сгенерируйте случайный ключ и передайте его через окружение.'
    )

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Нужен для триграммного поиска позиций (pg_trgm)
    'django.contrib.postgres',

    # Third party
    'rest_framework',
    # Чёрный список refresh-токенов: нужен, чтобы logout и смена пароля
    # действительно отзывали доступ, а не ждали истечения токена.
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'drf_spectacular',

    # Local apps
    'users.apps.UsersConfig',
    'posts.apps.PostsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Перебор на форме входа в админку — см. users/middleware.py
    'users.middleware.AdminLoginRateLimitMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'foody'),
        'USER': os.environ.get('POSTGRES_USER', 'foody'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# UI сервиса русский — стандартные сообщения валидации Django/DRF
# (unique, required, throttled, пароли) должны приходить на русском
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Custom Authentication Backends
AUTHENTICATION_BACKENDS = [
    'users.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Media Settings (for Avatars & Posts)
# Путь переопределяется через MEDIA_ROOT: в контейнере это примонтированный том,
# а при локальном запуске каталог backend/media принадлежит root (его создал Docker),
# и Django в него писать не может — тогда указываем свой.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT') or (BASE_DIR / 'media'))

# CORS Config
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]

# CSRF trusted origins (for HTTPS behind reverse proxy)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Reverse proxy / HTTPS termination (Caddy)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# REST Framework Setup
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Обязательная пагинация по размеру страницы (PAGE_SIZE) из ENV
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': get_env_int('PAGE_SIZE', 20),

    # Дефолтный поиск по всем вьюхам, где указан filter_backends
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # OpenAPI схема через drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Rate limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'login': '10/minute',
        # Письма и коды: перебор шестизначного кода и рассылка писем на чужой
        # ящик — обе угрозы упираются в этот лимит.
        'email_code': '30/hour',
        'user': '300/minute',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Foody API',
    'DESCRIPTION': 'Социальная сеть для гастрономических постов',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Максимальная оценка для отзывов (PostReview). Можно изменить через ENV и перезапустить Django.
MAX_REVIEW_RATING = get_env_int('MAX_REVIEW_RATING', 10)

# Порог доверия в байесовской формуле рейтинга позиции («m»). Чем больше, тем сильнее
# рейтинг позиции с малым числом оценок притягивается к среднему по сервису.
RATING_PRIOR_COUNT = get_env_int('RATING_PRIOR_COUNT', 5)
# Среднее по сервису («C») меняется медленно — держим в кэше, чтобы одобрение
# каждого поста не тянуло агрегат по всей таблице позиций.
RATING_GLOBAL_AVG_TTL = int(get_env_time_interval('RATING_GLOBAL_AVG_TTL', '1h'))

# --- Яндекс.Карты ---------------------------------------------------------
# Продукты (JavaScript API, Геосаджест, Геокодер) подключаются в Кабинете разработчика
# и активируются не мгновенно: на практике около часа, а не заявленные 15 минут. Пока
# продукт не активирован, запросы к нему отвечают 403 «Invalid api key» при верном ключе.
#
# Ключ может быть один на все продукты или свой на каждый — поддерживаем оба варианта.
YANDEX_MAPS_API_KEY = os.environ.get('YANDEX_MAPS_API_KEY', '')  # JavaScript API (браузер)
# Серверный ключ для Геосаджеста. Если отдельной переменной нет — берём общий.
YANDEX_GEO_API_KEY = os.environ.get('YANDEX_GEO_API_KEY') or YANDEX_MAPS_API_KEY

YANDEX_API_TIMEOUT = get_env_int('YANDEX_API_TIMEOUT', 5)

# Суточный лимит Геосаджеста на бесплатном тарифе — 1000 запросов на весь сервис.
YANDEX_SUGGEST_DAILY_LIMIT = get_env_int('YANDEX_SUGGEST_DAILY_LIMIT', 1000)
# Держим часть квоты про запас для фонового обновления заведений, чтобы
# пользовательский поиск не съел её целиком.
YANDEX_SUGGEST_QUOTA_RESERVE = get_env_int('YANDEX_SUGGEST_QUOTA_RESERVE', 200)
# Не ходим в API на слишком короткий ввод — осмысленных подсказок там нет,
# а квота тратится.
YANDEX_SUGGEST_MIN_QUERY_LENGTH = get_env_int('YANDEX_SUGGEST_MIN_QUERY_LENGTH', 3)
YANDEX_SUGGEST_RESULTS = get_env_int('YANDEX_SUGGEST_RESULTS', 7)
# Размер окна поиска в градусах. Без окна выдача разбросана по всей стране.
YANDEX_SUGGEST_DEFAULT_SPN = os.environ.get('YANDEX_SUGGEST_DEFAULT_SPN', '0.3,0.3')
# Сервис работает только по России, поэтому подсказки ограничиваем страной.
YANDEX_SUGGEST_COUNTRIES = os.environ.get('YANDEX_SUGGEST_COUNTRIES', 'ru')
# Кэш ответов на одинаковые поисковые запросы — чтобы не выесть суточную квоту
# на повторных подсказках. Это кэш HTTP-запроса, а не хранение данных о заведениях:
# сам Яндекс такое кэширование рекомендует, потолок по их условиям — 30 дней.
YANDEX_SUGGEST_CACHE_TTL = int(get_env_time_interval('YANDEX_SUGGEST_CACHE_TTL', '7d'))

# Размер страницы для очереди модерации. Можно изменить через ENV и перезапустить Django.
MODERATION_PAGE_SIZE = get_env_int('MODERATION_PAGE_SIZE', 10)

# Вход в админку: сколько неудачных попыток с одного адреса терпим и на какое
# окно закрываемся после этого. Считаются только неудачи, успешный вход
# счётчик обнуляет, поэтому обычной работе администратора лимит не мешает.
ADMIN_LOGIN_MAX_ATTEMPTS = get_env_int('ADMIN_LOGIN_MAX_ATTEMPTS', 10)
ADMIN_LOGIN_ATTEMPT_WINDOW = get_env_time_interval('ADMIN_LOGIN_ATTEMPT_WINDOW', '5m')

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Почта
#
# Транзакционные письма (коды подтверждения и сброса пароля) уходят через
# внешний SMTP-релей: свой почтовый сервер на этом же VPS попадал бы в спам у
# mail.ru и Gmail без PTR, прогрева адреса и постоянной чистки блоклистов.
# Настройки все из окружения — сменить релей можно без правки кода.
#
# Без EMAIL_HOST письма печатаются в консоль. Это режим разработки: код видно
# в логах, почта не нужна, случайных писем живым людям не уходит.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
# EMAIL_FILE_PATH складывает письма файлами в указанную папку. Это удобнее
# консоли при локальной разработке: письмо отправляет Celery-воркер, и в
# консоли оно оказывается в его окне — не в том, где запущен Django, а под
# nohup не видно вовсе. Файл открывается когда угодно и кем угодно.
EMAIL_FILE_PATH = os.environ.get('EMAIL_FILE_PATH', '')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
elif EMAIL_FILE_PATH:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_PORT = get_env_int('EMAIL_PORT', 587)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = bool(int(os.environ.get('EMAIL_USE_TLS', '1')))
EMAIL_USE_SSL = bool(int(os.environ.get('EMAIL_USE_SSL', '0')))
EMAIL_TIMEOUT = get_env_int('EMAIL_TIMEOUT', 15)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Foody <noreply@foody.press>')

# Коды из писем
EMAIL_CODE_TTL = timedelta(seconds=get_env_time_interval('EMAIL_CODE_TTL', '15m'))
# Шесть цифр — миллион вариантов, автоматика переберёт их за минуты. Лимит
# попыток и есть то, что делает короткий код безопасным.
EMAIL_CODE_MAX_ATTEMPTS = get_env_int('EMAIL_CODE_MAX_ATTEMPTS', 5)
# Пауза между письмами: без неё формой можно завалить чужой ящик.
EMAIL_CODE_RESEND_COOLDOWN = timedelta(
    seconds=get_env_time_interval('EMAIL_CODE_RESEND_COOLDOWN', '60s'),
)
# Сколько держать отработавшие коды. Ноль пользы после того, как код потрачен
# или протух, — но пара суток помогает разбирать жалобы «код не приходил».
EMAIL_CODE_RETENTION = timedelta(
    seconds=get_env_time_interval('EMAIL_CODE_RETENTION', '2d'),
)
# Через сколько удалять регистрацию, которую не довели до конца.
#
# Дело не в мусоре, а в том, что такая запись держит адрес: email уникален, и
# пока она есть, настоящий владелец ящика зарегистрироваться не может. Неделя —
# запас на «указал почту, полез читать письмо, вернулся через выходные».
UNVERIFIED_ACCOUNT_TTL = timedelta(
    seconds=get_env_time_interval('UNVERIFIED_ACCOUNT_TTL', '7d'),
)

# Celery
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# Celery Beat tasks scheduling
CELERY_BEAT_SCHEDULE = {
    # Рейтинг позиции пересчитывается сразу при одобрении поста. Задача нужна для
    # другого: среднее по сервису со временем плывёт, а от него зависит рейтинг
    # каждой позиции. Плюс страховка от рассинхрона.
    'recalculate-menu-item-ratings': {
        'task': 'posts.tasks.recalculate_menu_item_ratings',
        'schedule': float(get_env_time_interval('RATING_RECALC_INTERVAL', '6h')),
    },
    # Брошенные регистрации держат чужие адреса — email уникален. Раз в сутки
    # достаточно: неделя ожидания против суток погрешности.
    'cleanup-email-codes': {
        'task': 'users.tasks.cleanup_email_codes',
        'schedule': float(get_env_time_interval('CLEANUP_INTERVAL', '24h')),
    },
    # Справочник заведений наш, значит и чистить дубли в нём нам.
    'find-restaurant-duplicates': {
        'task': 'posts.tasks.find_restaurant_duplicates',
        'schedule': float(get_env_time_interval('DUPLICATE_SCAN_INTERVAL', '24h')),
    },
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'posts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
