# Generated by Django 5.2.12 on 2026-03-25 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_dish_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='satiety',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='poststatistics',
            name='rating_appearance',
        ),
        migrations.RemoveField(
            model_name='poststatistics',
            name='rating_satiety',
        ),
        migrations.RemoveField(
            model_name='poststatistics',
            name='rating_taste',
        ),
        migrations.AddField(
            model_name='postreview',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='poststatistics',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Средняя оценка'),
        ),
    ]
