# Generated by Django 5.2.12 on 2026-03-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_moderated_at_post_moderated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.dish')),
            ],
            options={
                'unique_together': {('dish', 'category')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='posts.DishCategory', to='posts.category', verbose_name='Категории блюда'),
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'category')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', through='posts.RestaurantCategory', to='posts.category', verbose_name='Категории ресторана'),
        ),
    ]
