# Generated by Django 5.2.12 on 2026-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_backfill_dishcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
