# Generated by Django 5.2.12 on 2026-05-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_commentlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('restaurant', 'name')},
        ),
    ]
